services:
  dmr:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: whisperx-app
    env_file: cpu.env
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./db:/app/db
      - ./models:/app/models
