services:
  dmr:
    image: docker pull ghcr.io/loomiy/dmr-transcriber:latest
    env_file: .env
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./db:/app/db
      - ./cache:/root/.cache/huggingface
