FROM nvidia/cuda:13.3.0-cudnn-runtime-ubuntu24.04
 
WORKDIR /app
 
RUN apt-get update && apt-get install -y --no-install-recommends \
        python3 python3-pip ffmpeg \
    && rm -rf /var/lib/apt/lists/*
 
COPY requirements.txt .
RUN pip3 install --no-cache-dir --break-system-packages -r requirements.txt
 
COPY main.py .
 
CMD ["python3", "-u", "main.py"]
